### ISSUE TITLE
"Black" or Cancel?

### ISSUE THREAD

**Issue by therentabrain** [ungoogled-software/ungoogled-chromium#2023] opened 2022-07-22 23:31 UTC
What is going on with this?  Am I the first person to notice this typo or is there something wrong with my browser (a malware prank?)

When a form needs to be resubmitted to reload a page, the options I'm seeing are "black" or cancel.

"The page that you're looking for used information that you entered."

ETA: Ungoogled Chromium 101.0.4951.64

**Comment by therentabrain** [comment] 2022-07-22 23:31
![black](https://user-images.githubusercontent.com/6657421/180580512-69d32902-490b-41f1-b740-325d3d4b3c03.png)

**Comment by networkException** [comment] 2022-07-22 23:49
This has been brought up before in our chat room: https://matrix.to/#/!aQuneOjyFrLDdMEKjj%3Agitter.im/%24ORgu9hX7m1BIqVv7FuV8HHLPlr-uRRu16Rgnyqqn8eA

**Comment by therentabrain** [comment] 2022-07-23 00:00
I've never used the matrix/glitter platform, and I can't seem to get it working in browser right now (even by googling to try to find the conversation) but as long as it's a known issue and there's nothing to worry about, I guess I'll let it go :)

thanks!

**Comment by networkException** [comment] 2022-07-23 06:04
So we didn't really reach any conclusion. The person reporting back then was using Windows builds from winget which are considered third party (see https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/150) and as such not supported by us.

**Comment by tomasz1986** [comment] 2022-07-23 09:40
If it's a build from https://github.com/macchrome/winchrome/releases, then I'd assume it's probably a similar case as in https://github.com/ungoogled-software/ungoogled-chromium/issues/1714. I've never seen such errors in the releases from https://github.com/ungoogled-software/ungoogled-chromium-windows/releases (but at that time those were heavily outdated, so https://github.com/macchrome/winchrome/releases was the only source of up-to-date builds back then).

**Comment by networkException** [comment] 2022-07-23 09:42
I think I'll close this as a duplicate of #1714 then, these kinds of issues are very weird :shrug:

**Closed by networkException** 2022-07-23 09:42 UTC
