### ISSUE TITLE
Using performance patches from Thorium project

### ISSUE THREAD

**Issue by h4ckee** [ungoogled-software/ungoogled-chromium#2969] opened 2024-08-01 12:23 UTC
### Description

Using performance patches from Thorium project

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Hi guys.
I've used Thorium browser (https://thorium.rocks) for awhile but found it a bit bloated, but it runs pretty fast, you can check the speed on https://browserbench.org/Speedometer3.0
As for Ungoogled-Chromium, in many cases it consumes CPU (even with libva-intel-driver in my case), when watching videos on Youtube.

### Possible solutions

Don't you want to implement some of performance paches from Thorium to speed Ungoogled-Chromium up?
Best regards,
Sergey.

**Comment by PF4Public** [comment] 2024-08-01 15:03
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium/discussions/2372?

**Comment by rany2** [comment] 2024-08-01 15:22
At any rate, we aren't able to address compiler bugs which will definitely arise because of enabling such optimizations and really if Google doesn't have the capacity to deal with such issues and doesn't think it's worthwhile then it's really not worth it.

**Closed** 2024-08-01 15:36 UTC
Labels: enhancement, help wanted
