### ISSUE TITLE
Invalid Signature Ubuntu 20.04

### ISSUE THREAD

**Issue by bullionbob** [ungoogled-software/ungoogled-chromium#2101] opened 2022-09-28 20:27 UTC
**Describe the bug**
Receive an Invalid Signature error when attempting to install from the Downloads page.

**To Reproduce**
Run the following commands
```
echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/ /' | sudo tee /etc/apt/sources.list.d/home-ungoogled_chromium.list > /dev/null
 curl -s 'https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/Release.key' | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home-ungoogled_chromium.gpg > /dev/null
 sudo apt update
```

**Expected behavior**
The repository to be updated with ungoogled-chromium

**Environment (please complete the following information):**
OS: Ubuntu 20.04.5 LTS
Kernel: 5.15.0-48-generic

**Error**
`Err:8 http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease
  The following signatures were invalid: EXPKEYSIG 02456C79B2FD48BF home:ungoogled_chromium OBS Project <home:ungoogled_chromium@build.opensuse.org>
Reading package lists... Done       
W: GPG error: http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease: The following signatures were invalid: EXPKEYSIG 02456C79B2FD48BF home:ungoogled_chromium OBS Project <home:ungoogled_chromium@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
After sudo apt update

**Comment by networkException** [comment] 2022-09-28 20:35
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/307

**Closed by networkException** 2022-09-28 20:35 UTC
