### ISSUE TITLE
Enable "about:blank" To Respect Dark Theme

### ISSUE THREAD

**Issue by p0da** [ungoogled-software/ungoogled-chromium#2061] opened 2022-08-24 05:46 UTC
### Description

The about:blank page does not respect dark mode flags.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Currently, regardless of the dark mode flag combination, the about:blank page does not seem to become black. It is exclusively white. This is especially annoying/obvious when setting about:blank as the new tab page when using a dark theme.

### Possible solutions

Implement additional logic enabling about:blank to respect dark mode.

**Comment by PF4Public** [comment] 2022-08-24 13:10
Cannot reproduce on Gentoo:
![image](https://user-images.githubusercontent.com/10319700/186426749-f09bedea-98cc-47fd-9de8-63ee00cab4b5.png)

**Comment by p0da** [comment] 2022-08-24 20:51
Hmm, do you happen to have the -enable-features=WebContentsForceDark set? I personally don't use that feature due to the lack of a per site toggle. It does however result in the requested behavior for about:blank. This feature would be more akin to how the default new tab page conforms to the dark/light mode without requiring WebContentsForceDark.

**Comment by PF4Public** [comment] 2022-08-24 21:51
> Hmm, do you happen to have the -enable-features=WebContentsForceDark set?

I have chrome://flags/#enable-force-dark set. Is it the same as -enable-features=WebContentsForceDark?

**Comment by p0da** [comment] 2022-08-25 04:32
Checking chrome://version/ it seems like it is; which does make sense.

**Comment by PF4Public** [comment] 2022-08-25 10:27
> If you disable it do you get a white about:blank?

Yep, it is white

**Comment by p0da** [comment] 2022-08-25 18:51
My current dark mode flag setup is WebUIDarkMode in --enable-features and --force-dark-mode.

**Comment by uhthomas** [comment] 2023-01-12 23:36
I also see this behaviour on Arch Linux. I imagine this is because of how Chromium interacts with Wayland and would need to be fixed upstream really.

https://bugs.chromium.org/p/chromium/issues/detail?id=998903

**Comment by daemonjax** [comment] 2023-02-20 02:04
Instead of using a blank page, I have it use a custom local html page that's black.

**Comment by PF4Public** [comment] 2023-06-10 23:00
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Closed by PF4Public** 2023-06-10 23:00 UTC
Labels: enhancement, help wanted
