### ISSUE TITLE
Build failed when Running gsync: The system cannot find the path specified

### ISSUE THREAD

**Issue by TenmaSennpai** [ungoogled-software/ungoogled-chromium#2684] opened 2024-01-20 22:00 UTC
### OS/Platform

Windows

### Installed

Compiled from source

### Version

120.0.6099.224

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

When I run python3 build.py：The system cannot find the path specified.

### How to Reproduce?

When I run python3 build.py：The system cannot find the path specified.

### Actual behaviour

Looks like a gclient sync error.
Help me, please.

### Expected behaviour

normal

### Relevant log output

```sh
INFO: Cloning gn
Cloning into 'build\src\uc_staging\gn'...
remote: Total 32636 (delta 17202), reused 32636 (delta 17202)
Receiving objects: 100% (32636/32636), 33.16 MiB | 20.88 MiB/s, done.
Resolving deltas: 100% (17202/17202), done.
INFO: Running gsync
The system cannot find the path specified.
Traceback (most recent call last):
File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 294, in
main()
File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 290, in main
clone(args)
File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 124, in clone
run([str(gcpath), 'sync', '-f', '-D', '-R', '--no-history', '--nohooks'], check=True)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['build\src\uc_staging\depot_tools\gclient.bat', 'sync', '-f', '-D', '-R', '--no-history', '--nohooks']' returned non-zero exit status 1.
Traceback (most recent call last):
File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\build.py", line 257, in
main()
File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\build.py", line 179, in main
subprocess.run([sys.executable, str(Path('ungoogled-chromium', 'utils', 'clone.py')), '-o', 'build\src', '-p', 'win32' if args.x86 else 'win64'], check=True)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python3.exe', 'ungoogled-chromium\utils\clone.py', '-o', 'build\src', '-p', 'win64']' returned non-zero exit status 1.
```

**Comment by PF4Public** [comment] 2024-01-21 10:19
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/313?

**Comment by TenmaSennpai** [comment] 2024-01-21 10:22
> Duplicate of [ungoogled-software/ungoogled-chromium-windows#313](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/313)?

yes, same error message as that guy.

**Comment by TenmaSennpai** [comment] 2024-01-21 10:23
> Duplicate of [ungoogled-software/ungoogled-chromium-windows#313](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/313)?

yes, I closed that one.

**Comment by PF4Public** [comment] 2024-01-21 10:24
> yes, I closed that one.

Which was a duplicate of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/306 :D Why?

**Comment by TenmaSennpai** [comment] 2024-01-22 18:13
> Which was a duplicate of [ungoogled-software/ungoogled-chromium-windows#306](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/306) :D Why?

no response

**Closed** 2024-02-13 11:04 UTC
Labels: bug
