### ISSUE TITLE
Create extension for automatic update

### ISSUE THREAD

**Issue by ivanjaros** [ungoogled-software/ungoogled-chromium#2185] opened 2022-12-09 17:11 UTC
### Description

Request for extension(can be shipped with binary) that will implement automatic check and download of new updates to keep up-to-date without having to manually check, download and install new versions. Especially for windows.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Requirement to manually check, download and install new versions.

### Possible solutions

A chromium extension that will do it automatically(check, download, install... or all three, based on settings).

**Comment by networkException** [comment] 2022-12-09 17:15
Duplicate of (for example) #1358. In general we are not interested in providing built in updates, there are plenty of external tools (package managers) users can rely on like `winget`, `pacman` and so on

**Closed by networkException** 2022-12-09 17:15 UTC
Labels: enhancement, help wanted

**Comment by claudiodekker** [comment] 2024-02-06 16:40
Since this appears to be a common and recurring issue (arguably for good reason), I figured I'd try to partially address it by creating **a Chromium extension that automatically checks for new Chromium updates in-line with your preferences**.

Its functionality resembles that of NeverDecaf's "Chromium Web Store" extension: It displays a badge indicating available updates and, when interacted with, provides a concise overview of all available updates, allowing you to directly download newer build versions, jump to the release page, copy hashes and more. Essentially, it serves as the closest thing to an automated updater mechanism, without one being built-in.

You can find it here: https://github.com/claudiodekker/chromium-update-notifier
