### ISSUE TITLE
Secure DNS fails on .works domain

### ISSUE THREAD

**Issue by Nifury** [ungoogled-software/ungoogled-chromium#2963] opened 2024-07-28 16:59 UTC
When Secure DNS is turned on and set to use anything other than OS default, `.works` domain cannot be resolved and returns `ERR_NAME_NOT_RESOLVED`. 

Example: https://howhttps.works/

I'm not sure if this issue is specific to UG, but I cannot reproduce it on Chrome.

**Comment by PF4Public** [comment] 2024-07-29 15:49
@Ahrotahn Could you reproduce this issue on your system?

**Comment by rany2** [comment] 2024-07-29 16:15
It might have nothing to do with `.works`. I could resolve `19216811.works` for example, maybe the fact that the domain contains `https` is the problem?

**Comment by Ahrotahn** [comment] 2024-07-29 17:46
I can reproduce this.  It only seems to be an issue for howhttps.works, other .works addresses function normally like the one @rany2 mentioned.  

Even weirder, if you visit howhttps.works once without secure DNS enabled then the site will work fine afterwards once it's re-enabled.  This works on other pages on the domain and with a hard refresh so it isn't just a cached version of the page.

**Comment by PF4Public** [comment] 2024-07-29 20:29
> Even weirder, if you visit howhttps.works once without secure DNS enabled then the site will work fine afterwards once it's re-enabled. This works on other pages on the domain and with a hard refresh so it isn't just a cached version of the page.

Same for me.

**Comment by networkException** [comment] 2024-07-29 22:47
maybe something to do with HSTS?

**Comment by alienbob** [comment] 2024-07-30 18:50
I just upgraded to my fresh Un-Googled Chromium 127 on Slackware, switched on Secure DNS and accessed https://howhttps.works/ .
It works, No errors or issues and I get to see the page - and I honestly never visited this URL before, did not knw of its existence.
Examining the network interactions (which I did activate via Developer Tools before accessing this URL for the first time) I only see loading error for https://tag.getdrip.com/9686301.js due to `Referrer Policy: "strict-origin-when-cross-origin"`.

**Comment by rany2** [comment] 2024-07-30 18:54
@alienbob Did you access it without secure DNS beforehand? See https://github.com/ungoogled-software/ungoogled-chromium/issues/2963#issuecomment-2256554151

**Comment by alienbob** [comment] 2024-07-30 18:57
> @alienbob Did you access it without secure DNS beforehand? See [#2963 (comment)](https://github.com/ungoogled-software/ungoogled-chromium/issues/2963#issuecomment-2256554151)

Nope. As I said (but pashaps not explicitly enough) , I had never even heard of the site, and turned on Secure DNS **before** accessing that URL for the first time.

**Comment by Ahrotahn** [comment] 2024-07-30 19:19
So I figured out what's going on.  An IPv6 check is being performed (I guess due to the site having an IPv6 address available?) and `add-ipv6-probing-option.patch` is forcing a true value unless `--enable-features=SetIpv6ProbeFalse`/`chrome://flags/#set-ipv6-probe-false` is set.  Enabling that flag allows the site to function normally for me.  

I think it'll be a good idea to update that patch to return the actual result rather than always assuming true.  Then the flag could just override that value.  Alternatively we could default to false since it does that already for those on wifi:  https://source.chromium.org/chromium/chromium/src/+/refs/tags/127.0.6533.72:net/dns/host_resolver_manager.cc;l=1423-1430

I assume that @alienbob has IPv6 connectivity and that those of us encountering the issue don't?

**Comment by Nifury** [comment] 2024-07-30 19:35
Interesting finding! I do have IPv6 connectivity and the site seems to return IPv4 addresses only, but enabling that flag works for me as well.

**Comment by alienbob** [comment] 2024-07-30 19:50
> I assume that @alienbob has IPv6 connectivity and that those of us encountering the issue don't?

I don't have IPv6 connectivity where I ran the test.

**Comment by rany2** [comment] 2024-07-30 19:52
I do have IPv6 connectivity, that's not it.... Sorry :(

**Comment by PF4Public** [comment] 2024-07-30 20:06
IPv4-only host:
```sh
$ nslookup howhttps.works
[...]
Non-authoritative answer:
Name:	howhttps.works
Address: ***IPv4***
Name:	howhttps.works
Address: ***IPv4***
```

IPv6+IPv4 host:
```sh
$ nslookup howhttps.works
[...]
Non-authoritative answer:
Name:	howhttps.works
Address: ***IPv4***
Name:	howhttps.works
Address: ***IPv4***
** server can't find howhttps.works: SERVFAIL
```

The last one is actually trying to resolve AAAA, but fails:
![image](https://github.com/user-attachments/assets/03e205c8-cbe6-471c-a262-b90150355f56)

So it might indeed be trying to resolve IPv6 through DoH and fails.

**Comment by PF4Public** [comment] 2024-09-02 17:42
So I'm closing this as `wontfix` unless we get more of similarly troubling websites.

**Closed by PF4Public** 2024-09-02 17:42 UTC
Labels: wontfix
