### ISSUE TITLE
"Always show full URLs" toggle doesn't work

### ISSUE THREAD

**Issue by achtchaern** [ungoogled-software/ungoogled-chromium#2177] opened 2022-12-05 23:03 UTC
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

108.0.5359.95

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

"Always show full URLs" toggle doesn't work

### How to Reproduce?

1. Go on any website
2. Right-click on the URL in the address bar
3. Toggle on the option "Always show full URLs"
4. Check if anything changed
5. Toggle on the option "Always show full URLs" again
6. Check if anything changed

### Actual behaviour

Nothing changes. The full URL is being displayed, even if the setting "Always show full URLs" is disabled

### Expected behaviour

The URL should get shortened (e.g. "https://" would not be displayed), as it does in regular Chrome and Chromium.

**Comment by PF4Public** [comment] 2022-12-06 17:37
Duplicate of #2163

**Closed by PF4Public** 2022-12-06 17:37 UTC
Labels: bug
