### ISSUE TITLE
"Spotify can't play this right now"

### ISSUE THREAD

**Issue by ygxrr** [ungoogled-software/ungoogled-chromium#2992] opened 2024-08-18 18:58 UTC
### OS/Platform

Windows

### Installed

OS/Platform's package manager

### Version

127.0.6533.119

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Everytime i try to play a song on Spotify it shows an message on the bottom saying "Spotify can't play this right now" and then all songs starts to skip itself every 2 seconds, i didnt had this issue on ungoogled-chromium with my netbook running Void Linux

### How to Reproduce?

Try to play a song on open.spotify.com

### Actual behaviour

Spotify shows "Spotify can't play this right now" and starts to skip songs in every 2 seconds showing the same message

### Expected behaviour

Spotify should play a song

**Comment by PF4Public** [comment] 2024-08-18 19:08
Duplicate of #1258

**Closed by PF4Public** 2024-08-18 19:08 UTC
Labels: bug

**Comment by ygxrr** [comment] 2024-08-19 14:19
so theres no fix? it seems to be an really old issue

**Comment by PF4Public** [comment] 2024-08-19 15:18
No one examined the issue in details and therefore the root cause wan't identified.
