### ISSUE TITLE
Please give back the ability to set Google as the default search engine.

### ISSUE THREAD

**Issue by Tommy2678** [ungoogled-software/ungoogled-chromium#2796] opened 2024-04-10 19:38 UTC
### Description

Give back the ability to set Google as the default search engine.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I'm frustrated when I have to use a separate search engine that is either too slow, or gives inaccurate results to what I want. Going to google.com is inconvenient for each time I want to search something on google.

This is very bad especially when I need to look up some stuff for my schoolwork. On Google, they use my previous results to provide me with relevant answers, on anything else I will get something completely irrelevant.

I understand that the point of ungoogled chromium is to get rid of google, but switching your search engine to something not on the list should be a feature.

### Possible solutions

Readd or let us add our own search engines in the search engine settings page.

**Comment by networkException** [comment] 2024-04-10 19:39
Duplicate of #2730

**Closed by networkException** 2024-04-10 19:39 UTC
Labels: enhancement, help wanted
