### ISSUE TITLE
"Cast..." context menu item

### ISSUE THREAD

**Issue by artur-intech** [ungoogled-software/ungoogled-chromium#2199] opened 2023-01-01 00:23 UTC
I don't use Chromecast, so the menu item there just takes space. I wonder whether it could be removed using the flag, for example.

**Comment by uhthomas** [comment] 2023-01-12 23:27
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium/issues/2193.

**Closed** 2023-01-12 23:49 UTC
Labels: enhancement, help wanted
