### ISSUE TITLE
annoying message for Win7/8/8.1 users since Chromium 108

### ISSUE THREAD

**Issue by stano22** [ungoogled-software/ungoogled-chromium#2187] opened 2022-12-12 16:00 UTC
Hi team,
many thanks for your nice work regarding this project.
I use Win7 (also I will continue to use Win7) and since version 108, there is annoying message/warning with every run of ungoogled-chromium:
"To get future Chromium updates, you´ll need Windows 10 or later. This computer is using Windows 7."
There is a solution to create a new registry entry for Chromium policies (SuppressUnsupportedOSWarning), but after using this workaround, Chromium will state "Managed by your organization" and it means another issue - Secure DNS is not available (grayed out) in browser Settings and therefore browser starts to use system DNS instead.
I cannot find any setting, flag or switch to remove this annoyance.
Is there any working solution or planned patch to get rid of this annoying message for Win7/8/8.1 users?

**Comment by networkException** [comment] 2022-12-12 18:49
Please do not create duplicate issues for platform specific feature requests.

Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/193

**Closed by networkException** 2022-12-12 18:49 UTC
