### ISSUE TITLE
Key at opensuse repository expired - please update

### ISSUE THREAD

**Issue by wolframd** [ungoogled-software/ungoogled-chromium#2030] opened 2022-07-31 21:52 UTC
### Description

Please update your key

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Hello, 

thank you so much for your fantastic work with ungoogled chromium browser! It's my main browser since several months now.

When I tried to install it on my Ubuntu machine I got the message that the key is expired at the opensuse.org - home: repository.

/etc/apt/trusted.gpg.d/home-ungoogled_chromium.gpg
--------------------------------------------------
pub   2048R/B2FD48BF 2020-04-24 [expired: 2022-07-03]
uid                  home:ungoogled_chromium OBS Project <home:ungoogled_chromium@build.opensuse.org>

### Possible solutions

 Could you perhaps update your signature there? That would be great!

**Comment by networkException** [comment] 2022-07-31 21:54
This is a duplicate of https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/307

Until the issue gets resolved you could for example install the flatpak version

**Closed by networkException** 2022-07-31 21:54 UTC
Labels: enhancement, help wanted
