### ISSUE TITLE
Shipping broken in Arch Linux AUR repositories

### ISSUE THREAD

**Issue by s1nistr4** [ungoogled-software/ungoogled-chromium#2270] opened 2023-03-13 22:20 UTC
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

111.0.5563.64-2

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

ungoogled-chromium-bin is shipping broken in the official Arch linux repos and is impossible to install

### How to Reproduce?

1. yay -S ungoogled-chromium-bin
2. Wait for it to finish
3. Open it, nothing happens

### Actual behaviour

It doesn't open and gives the error `/usr/lib/chromium/chromium: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory`

### Expected behaviour

For it to open

### Relevant log output

```sh
`/usr/lib/chromium/chromium: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory`
```

**Comment by networkException** [comment] 2023-03-13 22:21
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/222

**Closed by networkException** 2023-03-13 22:21 UTC
Labels: bug
