### ISSUE TITLE
search engine modification

### ISSUE THREAD

**Issue by Quetzaal** [ungoogled-software/ungoogled-chromium#2004] opened 2022-06-26 16:28 UTC
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

102.0.5005.61

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

no way to valid modification or new search engine

### How to Reproduce?

go to serach engine
add a new search engine or click on the "new" pencil icon to modify the engine
add information, or modify them
click on validation
and chromium close, after repoen the new or the modification are not recorded

### Actual behaviour

close when it clicked on valid new or after modification of search engine

### Expected behaviour

to valid and record modification or new search engines

### Additional context

it was working without problem before 102.0.500 on 101.x.xxx
i've update these two version quickly in time, and ass a lot search engine with 101.x.xxx
and did nothing since this afternoon with 102.0.500 

not fun, but i can go back to 101.x.xxx

**Comment by networkException** [comment] 2022-06-26 16:36
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/189, this has been fixed in https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/102.0.5005.61-2. Please install an up to date version

**Closed by networkException** 2022-06-26 16:36 UTC
Labels: bug

**Comment by Quetzaal** [comment] 2022-06-26 21:14
thanks... 
sorry for posting without to have read all the issue...

**Comment by networkException** [comment] 2022-06-26 21:16
its fine, thats why there are maintainers to keep track of everything :)
