### ISSUE TITLE
APT Expired Signature

### ISSUE THREAD

**Issue by arminfelder** [ungoogled-software/ungoogled-chromium#2027] opened 2022-07-25 22:30 UTC
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

OS/Platform's package manager

### Version

all

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Repository signature expired

### How to Reproduce?

echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Bullseye/ /' | tee /etc/apt/sources.list.d/home-ungoogled_chromium.list > /dev/null
curl -s 'https://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Bullseye/Release.key' | gpg --dearmor | tee /etc/apt/trusted.gpg.d/home-ungoogled_chromium.gpg > /dev/null

apt-get update && apt-get install --no-install-recommends -y jq ungoogled-chromium

### Actual behaviour

EXPKEYSIG 02456C79B2FD48BF home:ungoogled_chromium OBS Project <home:ungoogled_chromium@build.opensuse.org>

### Expected behaviour

Signature should be valid, so APT wold accept it

### Relevant log output

```sh
curl -s 'https://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Bullseye/Release.key' | gpg

gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048 2020-04-24 [SC] [expired: **2022-07-03**]
      157C212D66D9B95118C5EDD302456C79B2FD48BF
uid           home:ungoogled_chromium OBS Project <home:ungoogled_chromium@build.opensuse.org>
```

**Comment by networkException** [comment] 2022-07-25 22:35
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/307

I moved your previous issue to the relevant repository.

**Closed by networkException** 2022-07-25 22:35 UTC
Labels: bug
