### ISSUE TITLE
Build fails with undecipherable messages about a nonexistent macro

### ISSUE THREAD

**Issue by TCH68k** [ungoogled-software/ungoogled-chromium#2421] opened 2023-07-20 23:23 UTC
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

115.0.5790.99

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

During boot, it dies off telling there is no TQ_OBJECT macro in a header.

### How to Reproduce?

1. Use this `flags.gn`:
```
build_with_tflite_lib=false
chrome_pgo_phase=0
clang_use_chrome_plugins=false
disable_fieldtrial_testing_config=true
enable_hangout_services_extension=false
enable_mdns=false
enable_mse_mpeg2ts_stream_parser=true
enable_nacl=false
enable_reading_list=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_widevine=true
exclude_unwind_tables=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
safe_browsing_mode=0
treat_warnings_as_errors=false
use_official_google_api_keys=false
use_unofficial_version_number=false

is_official_build=true
is_chrome_branded=false
is_chrome_for_testing=false
is_chrome_for_testing_branded=false

is_clang=true
is_component_build=false
optimize_webui=true

is_debug=false
symbol_level=0
blink_symbol_level=0
v8_symbol_level=0
v8_enable_backtrace=false
enable_iterator_debugging=false
blink_enable_generated_code_formatting=false

dcheck_always_on=false
is_cfi=false
use_thin_lto=false
angle_build_tests=false
build_dawn_tests=false
build_libsrtp_tests=false
enable_assistant_integration_tests=false
enable_downstream_media_tests=false
enable_nocompile_tests=false
enable_perfetto_integration_tests=false
enable_perfetto_unittests=false
enable_printing_unittests=false
enable_soda_integration_tests=false
force_enable_fieldtrial_testing_config=false
internal_gles2_conform_tests=false
internal_khronos_glcts_tests=false
rtc_include_tests=false
skia_enable_skshaper_tests=false
tint_build_unittests=false
use_base_test_suite=false
use_rts=false

use_gnome_keyring=false
use_pulseaudio=false
link_pulseaudio=false
use_alsa=true
use_cups=true
use_goma=false
use_kerberos=false
use_gio=true
use_sysroot=false
use_vaapi=true
enable_vr=false

enable_ffmpeg_video_decoders=true
media_use_ffmpeg=true
proprietary_codecs=true
ffmpeg_branding="Chrome"
use_webaudio_ffmpeg=true
use_webaudio_pffft=false

ozone_auto_platforms=false
ozone_platform="x11"
ozone_platform_cast=false
ozone_platform_drm=false
ozone_platform_flatland=false
ozone_platform_gbm=false
ozone_platform_headless=false
ozone_platform_scenic=false
ozone_platform_wayland=false
ozone_platform_x11=true
use_ozone=true
```
2. Build

### Actual behaviour

Dies of with this error message:
```
FAILED: gen/qt_shim_moc.cc
python3 ../../ui/qt/moc_wrapper.py ../../ui/qt/qt_shim.h gen/qt_shim_moc.cc
../../ui/qt/qt_shim.h:55: Error: The declaration of the class "QtShim" contains signals or slots
         but no TQ_OBJECT macro.
Traceback (most recent call last):
  File "/root/kocsog_gugli/chromium/src/out/Release/../../ui/qt/moc_wrapper.py", line 10, in <module>
    subprocess.check_call(["moc", sys.argv[1], "-o", sys.argv[2]])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['moc', '../../ui/qt/qt_shim.h', '-o', 'gen/qt_shim_moc.cc']' returned non-zero exit status 1.
```

### Expected behaviour

Build.

### Relevant log output

```sh
FAILED: gen/qt_shim_moc.cc
python3 ../../ui/qt/moc_wrapper.py ../../ui/qt/qt_shim.h gen/qt_shim_moc.cc
../../ui/qt/qt_shim.h:55: Error: The declaration of the class "QtShim" contains signals or slots
         but no TQ_OBJECT macro.
Traceback (most recent call last):
  File "/root/kocsog_gugli/chromium/src/out/Release/../../ui/qt/moc_wrapper.py", line 10, in <module>
    subprocess.check_call(["moc", sys.argv[1], "-o", sys.argv[2]])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['moc', '../../ui/qt/qt_shim.h', '-o', 'gen/qt_shim_moc.cc']' returned non-zero exit status 1.
```

### Additional context

Seems to be bypassable by setting `use_qt` to `false`, but it should not fail because of that.
Note: PyQt and PySide2 IS installed. (Python3.9 / Qt 5.15.2)

**Comment by PF4Public** [comment] 2023-08-11 18:54
Have you found a solution?

**Comment by TCH68k** [comment] 2023-08-11 21:13
No, i have not.

**Comment by PF4Public** [comment] 2023-08-11 22:31
The problem is their tendency to use bundled things, which complicates things. You need to do some trickery with qt paths to make it work. See for example, how Gentoo does that: https://github.com/gentoo/gentoo/blob/11ca48169618e6ff6389697a25487def407d332e/www-client/chromium/chromium-115.0.5790.170.ebuild#L957-L985

**Comment by TCH68k** [comment] 2023-08-12 01:13
Thanks. So, i have to add
```
use_qt=true
use_qt6=false
moc_qt5_path="/usr/lib/x86_64-linux-gnu/qt5/bin/"
use_system_libffi=true
ozone_platform_x11=true
ozone_platform_wayland=false
ozone_platform="x11"
```
to `flags.gn`. The latter three is already in, so i have to add the rest only.
BTW, why is setting Ozone's backend is so redundant? Would not be
```
ozone_platform_x11=true
ozone_platform_wayland=false
```
or
```
ozone_platform="x11"
```
enough?

**Comment by PF4Public** [comment] 2023-08-12 13:56
> BTW, why is setting Ozone's backend is so redundant?

You mean why is it so detailed in Gentoo? Because https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ozone_overview.md#linux-desktop-x11-waterfall:

>By default, Linux enables the following Ozone backends - X11, Wayland and Headless.

Please do not use issue tracker as a chat. We expect this issue tracker to be used solely for the issues with ungoogled-chromium itself and not as a general FAQ about building Chromium from source. Please try doing your own research on this first. 

I'll close this issue as it is not an issue of ungoogled-chromium.

**Closed by PF4Public** 2023-08-12 13:56 UTC
Labels: bug, need info

**Comment by TCH68k** [comment] 2023-08-12 19:51
I did as you told. `flags.gn`:
```
use_system_libffi=true

ozone_auto_platforms=false
ozone_platform="x11"
ozone_platform_cast=false
ozone_platform_drm=false
ozone_platform_flatland=false
ozone_platform_gbm=false
ozone_platform_headless=false
ozone_platform_scenic=false
ozone_platform_wayland=false
ozone_platform_x11=true
use_ozone=true

use_gtk=false
use_aura=false
use_qt=true
use_qt6=false
moc_qt5_path="/usr/lib/x86_64-linux-gnu/qt5/bin/"
```
Result:
```
ERROR at //ui/wm/BUILD.gn:10:1: Assertion failed.
assert(use_aura)
^-----
See //ui/aura/BUILD.gn:245:5: which caused the file to be included.
    "//ui/wm",
    ^--------
```

**Comment by TCH68k** [comment] 2023-08-24 09:41
Some updates:
According to this Arch bugticket (https://bugs.archlinux.org/task/76769) Qt5 cannot be used as the standalone TK, only in tandem with GTK3, or with Aura in this case. So, the solution would be that with Qt5 support enabled, Aura (or GTK3) must be enabled too, and the completed binary must be runned with option `--enable-features=AllowQt`.

So, i've set Aura to `true` too and started compiling. The result was the same as it was at the start:
```
[23449/53128] ACTION //ui/qt:generate_moc(//build/toolchain/linux:clang_x64)
FAILED: gen/qt_shim_moc.cc
python3 ../../ui/qt/moc_wrapper.py ../../ui/qt/qt_shim.h gen/qt_shim_moc.cc
../../ui/qt/qt_shim.h:55: Error: The declaration of the class "QtShim" contains signals or slots
         but no TQ_OBJECT macro.
Traceback (most recent call last):
  File "/root/kocsog_gugli/chromium/src/out/Release/../../ui/qt/moc_wrapper.py", line 10, in <module>
    subprocess.check_call(["moc", sys.argv[1], "-o", sys.argv[2]])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['moc', '../../ui/qt/qt_shim.h', '-o', 'gen/qt_shim_moc.cc']' returned non-zero exit status 1.
[23458/53128] ACTION //content/browser/devtools:devtools_resources_grit(//build/toolchain/linux:clang_x64)
ninja: build stopped: subcommand failed.
```
I've grepped all the files in the source dir for `moc_qt5_path` and none of the files contain it. No surprise, that it cannot find `moc`. Maybe it is Gentoo-related.

However, as a workaround, i found out, that if i change a line in the file `chromium/src/ui/qt/moc_wrapper.py` from
```
subprocess.check_call(["moc", sys.argv[1], "-o", sys.argv[2]])
```
to
```
subprocess.check_call(["/usr/lib/x86_64-linux-gnu/qt5/bin/moc", sys.argv[1], "-o", sys.argv[2]])
```
then this error ceases and building continues.

**Comment by PF4Public** [comment] 2023-08-24 09:45
> No surprise, that it cannot find `moc`. Maybe it is Gentoo-related.

Indeed Gentoo applies https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/files/chromium-qt6.patch

**Comment by TCH68k** [comment] 2023-08-24 14:26
The build successfully completed. However, it does not use Qt5 at all. I cannot switch to the Qt5 theme. It appears in the 'Appearance' menu, but i cannot switch.

`objdump -p ./chrome` also shows that there are no Qt5 libraries used.

**Comment by TCH68k** [comment] 2023-08-25 10:48
Okay, it turned out, that if i compile it **ALL** with the toolkits, then Qt5 works. Apparently it needs GTK3 for compiling. For running, not necessarily. If i run the Qt5-capable `chrome` without `LD_LIBRARY_PATH=/opt/gtk3/lib/`, then it still works and picks up the theme, but has no dialogs (Aura bug?) and all UI fonts became very small, albeit still readable.

Now, if the Qt5 support is only partial, then i understand that it needs Aura **or** GTK3...but why both? And why does GTK3 needs Aura now? It did not needed it before.
